GET http://localhost:3001/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2ODk0MjQ5MDQsImV4cCI6MTY4OTQyNDkxOX0.oy_6H-Zei6N9JBU04wHwbjsD2HHqVpF_GRQn339tdYU
###

POST http://localhost:3002/token
Content-Type: application/json

{
 "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2ODk0MjUyODJ9.pgF4ibVHZFjipbrhVByUKEex6HaPdd6r9qtVti7QmkU"
}


###
POST http://localhost:3002/login
Content-Type: application.json

{
 "email": "a@gmail.com"
}